name:                giacenza
version:             0.1.0.0
github:              "githubuser/giacenza"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/giacenza#readme>

dependencies:
- base >= 4.7 && < 5
- cassava
- containers
- foldl
- mtl
- protolude
- turtle
- vector
- bytestring
- streaming-cassava
- streaming-with
- streaming 
- time
- streaming-nonempty
- streaming-commons 
- filepath

ghc-options:
  - -Wall
library:
  source-dirs: src

executables:
  giacenza-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - giacenza

tests:
  giacenza-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - giacenza
